mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

mysite/mysite/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('bibliothek/', include('bibliothek.urls')),
    path('library/', include('library.urls')),
    path('shorturl/', include('shorturl.urls')),
    path('blog/', include('blog.urls')),
    path('magicball/', include('magicball.urls')),
    path('todo/', include('todo.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/shorturl/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'shorturl'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('redirect/<code>', views.redirect, name='redirect')
]

mysite/shorturl/models.py
from django.db import models


class Web_Url(models.Model):
    code = models.CharField(max_length=100)
    original_url = models.CharField(max_length=500)

    def __str__(self):
        return self.original_url

mysite/shorturl/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
import random
from .models import Web_Url
import string


def index(request):
    urls = Web_Url.objects.order_by('-id')
    return render(request, 'shorturl/index.html', {'urls': urls})


def add(request):
    user_url = request.POST['Web_Url']
    random_chars = ''
    for i in range(4):
        random_chars += random.choice(string.ascii_letters + string.digits)
    print(random_chars)
    code = Web_Url(code=random_chars, original_url=user_url)
    code.save()
    return HttpResponseRedirect(reverse('shorturl:index'))


def redirect(request, code):
    url_row = Web_Url.objects.get(code=code)

    return HttpResponseRedirect(url_row.original_url)

mysite/shorturl/templates/shorturl/index.html
<!--I am stuck but thinking that I create a new url for each small link, then that url automatically redirects to the original input site-->

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'shorturl/style.css' %}">

    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="header">
    <h1>URL Shortener</h1>
    <h3>Use the 'URL Shortener' to shorten a longer url into a manageable length that can be used for sharing.</h3>
</div>
    <div>
        <form action="{% url 'shorturl:add' %}" method="post" >
            {% csrf_token %}
            <h2>Add URL to Shorten:</h2>
            <input type="text" name="Web_Url">
            <br>
            {{ code }}
            <button id="save" type="submit">save</button>
        </form>
    </div>
    <div>
        <table>
            <tr>
                <th>Code</th>
                <th>Url</th>
            </tr>
            {% for url in urls %}
            <tr>
                <!--<td><a href="{{url.original_url}}">{{url.code}}</a></td>-->
                <td><a href="http://localhost:8000{% url 'shorturl:redirect' url.code %}">{{url.code}}</a></td>
                <td>{{url.original_url}}</td>
            </tr>
            {% endfor %}
        </table>

    </div>
</body>
</html>