mysite/bibliothek/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'bibliothek'
urlpatterns = [
    path('', views.index, name='index'),
    path('check_book/', views.check_book, name='check_book'),
    path('add_book/', views.add_book, name='add_book'),
    path('check_author/', views.check_author, name='check_author'),
    path('register/', views.register, name='register'),
    path('register_user/', views.register_user, name='register_user'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('checkout/', views.checkout, name='checkout')
]

mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

mysite/mysite/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('bibliothek/', include('bibliothek.urls')),
    path('library/', include('library.urls')),
    path('shorturl/', include('shorturl.urls')),
    path('blog/', include('blog.urls')),
    path('magicball/', include('magicball.urls')),
    path('todo/', include('todo.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/bibliothek/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model



class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateField('date published')
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    check_out = models.BooleanField(default=True)
    # user_check_out = models.ForeignKey(
    #     get_user_model(),
    #     on_delete=models.CASCADE
    # )

    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

mysite/bibliothek/views.py
# https://wsvincent.com/django-referencing-the-user-model/
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import random
from datetime import datetime
from .models import Book, Author
from django.db import models



@login_required(login_url='/bibliothek/register_user/')
def index(request):
    authors = Author.objects.all()
    books = Book.objects.all()
    return render(request, 'bibliothek/index.html', {'authors': authors, 'books': books})


def check_book(request):
    book_title = request.POST['Book']
    title = Book(title=book_title)
    title.save()
    return HttpResponseRedirect(reverse('bibliothek:index'))

def add_book(request):
    book_title = request.POST['book']
    author_id = request.POST['author_id']
    pub_date = request.POST['pub_date']
    pub_date = datetime.strptime(pub_date, '%Y-%m-%d')
    title = Book(title=book_title, author_id=author_id, pub_date=pub_date)
    title.save()
    return HttpResponseRedirect(reverse('bibliothek:index'))

def check_author(request):
    author = request.POST['Author']
    author_name = Author(name=author)
    author_name.save()
    return HttpResponseRedirect(reverse('bibliothek:index'))

def checkout(request):
    book_id = request.POST['book_id']
    # book = Book.objects.get(pk=book_id, user_check_out=user_check_out)
    book = Book.objects.get(pk=book_id)
    book.check_out = not book.check_out
    book.save()
    return HttpResponseRedirect(reverse('bibliothek:index'))


def register_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    login(request, user)
    return HttpResponseRedirect(reverse('bibliothek:index'))


def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('bibliothek:index'))
    return HttpResponseRedirect(reverse('bibliothek:register'))


def register(request):
    return render(request, 'bibliothek/register.html', {})


def logout_user(request):
    logout(request)
    return render(request, 'bibliothek/register.html', {})

mysite/bibliothek/templates/bibliothek/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


    <link rel="stylesheet" type="text/css" href="{% static 'bibliothek/style.css' %}">

</head>
<body>

<div class="container">
    <h2>Library</h2>


    <h3>Search the Catalog</h3>

    <table>
        <tr>
            <th>
                Book Title
            </th>
            <th>
                Author
            </th>
            <th>
                Published Date
            </th>
            <th>
                Book Availability

            </th>
        </tr>

        <tr>
            {% for book in books %}
            <td>
                {{ book.title }}
            </td>
            <td>
                {{ book.author }}
            </td>
            <td>
                {{ book.pub_date }}
            </td>

            <td>
                <form action="{% url 'bibliothek:checkout' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{book.id}}" name="book_id"/>
                    <button type="submit" value="Submit">{% if book.check_out %}checkin{% else %}checkout{% endif %}</button>
                </form>


            </td>
        </tr>

        {% endfor %}
    </table>


    <h3>Your Account</h3>

    <!--<p>Welcome, {{user.username}}</p>-->
    <a href="{% url 'bibliothek:logout_user' %}">logout</a>
    <ul>an input field to search for:
        <li>
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="book">
            </form>
        </li>
        <li>books that user currently has checked out</li>
    </ul>

    <h3>Add a book to the Catalog</h3>
    <div class="row">

        <div class="col s3">
            <p>Book Title</p>
             <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" name="book">
                    <option value="{{book.id}}">{{book.available}}</option></form>
            <!---->
<!--<select class="browser-default" name="author_id">-->
                <!--{% for book in books %}-->
                <!--<input type="text" name="book">{{book_title.name}}</input>-->
                <!--{% endfor %}-->
            <!--</select>-->
        </div>
        <div class="col s3">
            <p>Author</p>

            <select class="browser-default" name="author_id">
                {% for author in authors %}
                <option value="{{author.id}}">{{author.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col s3">
            <p>Publication Date</p>
            <input type="date" name="pub_date">
        </div>
        <div class="col s12">
            <br>
            <button type="submit" class="waves-effect waves-light btn-large">save</button>

            </form>
        </div>
    </div>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>  document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, options);
});</script>

</body>
</html>

mysite/bibliothek/templates/bibliothek/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


    <link rel="stylesheet" type="text/css" href="{% static 'bibliothek/style.css' %}">

</head>
<body>

<table>
    <tr>
        <td>
            <h2>Register</h2>
            <form action="{% url 'bibliothek:register_user' %}" method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username</td>
                        <td><input type="text" name="username"/></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><input type="text" name="email"/></td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td><input type="password" name="password"/></td>
                    </tr>
                </table>
                <button type="submit">register</button>
            </form>
        </td>
        <td>
            <h2>Login</h2>
            <form action="{% url 'bibliothek:login_user' %}" method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username</td>
                        <td><input type="text" name="username"/></td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td><input type="password" name="password"/></td>
                    </tr>
                </table>
                <button type="submit">login</button>
            </form>
        </td>
    </tr>

</table>
</body>
</html>